Script started on Wed 02 Dec 2020 07:43:08 PM PST
[?1034h============================================================== (unix1) 07:43 PM
/afs/cats.ucsc.edu/courses/cse112-wm/Languages/prolog/Examples/
bash 52$ cat -n allpairs.pl
     1	% $Id: allpairs.pl,v 1.3 2020-12-02 16:29:53-08 - - $ */
     2	
     3	%
     4	% Query pair will return all pairs.
     5	%
     6	
     7	positive(red).
     8	positive(green).
     9	positive(blue).
    10	negative(cyan).
    11	negative(magenta).
    12	negative(yellow).
    13	
    14	pair(Pos,Neg) :- positive(Pos), negative(Neg).
    15	
    16	allpairs :- pair(Pos,Neg), print( pair(Pos,Neg) ), nl, fail.
    17	
    18	
============================================================== (unix1) 07:43 PM
/afs/cats.ucsc.edu/courses/cse112-wm/Languages/prolog/Examples/
bash 53$ swipl
Welcome to SWI-Prolog (threaded, 64 bits, version 8.0.3)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
Please run ?- license. for legal details.

For online help and background, visit http://www.swi-prolog.org
For built-in help, use ?- help(Topic). or ?- apropos(Word).

?- [allpairs][allpairs].
true.

?- allpairs.
pair(red,cyan)
pair(red,magenta)
pair(red,yellow)
pair(green,cyan)
pair(green,magenta)
pair(green,yellow)
pair(blue,cyan)
pair(blue,magenta)
pair(blue,yellow)
false.

?- ^D
% halt
============================================================== (unix1) 07:43 PM
/afs/cats.ucsc.edu/courses/cse112-wm/Languages/prolog/Examples/
bash 54$ exit

Script done on Wed 02 Dec 2020 07:43:29 PM PST
